### ISSUE TITLE
"Windows cannot find 'shortcut'" even though it is in batmanager

### ISSUE THREAD

**Issue by lisaralon** [andrewralon/keycuts#69]
See screen shot. 

Repro:
Cmd prompt
'cu'

says it's invalid, but it's listed within the batmanager...?

![image](https://user-images.githubusercontent.com/45615601/54154563-8901a100-4418-11e9-82d7-93dffdad6710.png)

**Comment by andrewralon** [comment]
Can't reproduce -- looks like the shortcuts folder isn't in the windows path. That would explain this entirely.
